copy: Include pthread.h
OpenBSD's clang requires including pthread.h everywhere that threads
might be used.

In file included from null-ops.c:26:
./nbdcopy.h:85:3: error: unknown type name 'pthread_t'
  pthread_t thread;
  ^
1 error generated.