rust: Parse perlpod L<https://...> (external links) to rust markup
 Documenting libnbd v0.1.0 (/home/rjones/d/libnbd/rust)
error: this URL is not a hyperlink
    --> src/bindings.rs:2625:12
     |
2625 |     /// <i>https://gitlab.com/qemu-project/qemu/-/issues/2584</i>.
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: bare URLs are not automatically turned into clickable links
note: the lint level is defined here
    --> src/lib.rs:18:9
     |
18   | #![deny(warnings)]
     |         ^^^^^^^^
     = note: `#[deny(rustdoc::bare_urls)]` implied by `#[deny(warnings)]`
help: use an automatic link instead
     |
2625 |     /// <i><https://gitlab.com/qemu-project/qemu/-/issues/2584></i>.
     |            +                                                  +

error: could not document `libnbd`

Fixes: commit 07eb04a3033d85e0f7082b0a89bda839e688de40