tests/requires.c: Don't fail to compile if NBDKIT is not defined
On Fedora/i686 in particular, but also in general if nbdkit is not
around at compile time, the tests fail with:

requires.c: In function ‘requires_nbdkit_tls_verify_peer’:
requires.c:133:13: error: ‘NBDKIT’ undeclared (first use in this function)
  133 |   requires (NBDKIT " --tls-verify-peer -U - null --run 'exit 0'");
      |             ^~~~~~
requires.c:133:13: note: each undeclared identifier is reported only once for each function it appears in

Fixes: commit 9bc3478039be2cb1c9320f49fef1100dabf4c1a1