rust: Avoid compiler warning about unused import
On Fedora 39, cargo 1.75.0 complained:

   Compiling libnbd v0.1.0 (/home/eblake/libnbd/rust)
error: unused import: `async_bindings::*`
  --> src/lib.rs:31:9
   |
31 | pub use async_bindings::*;
   |         ^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:18:9
   |
18 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`

error: could not compile `libnbd` (lib) due to previous error

Since the presence of async_bindings is itself conditional on tokio,
it doesn't hurt to silence that particular warning.

Signed-off-by: Eric Blake <eblake@redhat.com>
Message-id: 20240105212815.1874107-1-eblake@redhat.com
Reviewed-by: Richard W.M. Jones <rjones@redhat.com>