ocaml/tests: Add explicit dependency on ocaml_test_config.cm{o,x}
Linking failed with:

File "_none_", line 1:
Error: Cannot find file ocaml_test_config.cmo

Fixes: commit fd5933e00fb2938d0a70ef159a02944c20a705e9